units:
  px: cx + 2
  py: cy + 2

  pushX: (cx / 2)
  pushY: (cy / 2)

  padX: pushX + 4
  padY: pushY + 4

  pad: 2

  spacing: 0.5

  diodeX: 3
  diodeY: 5
  contX: 21
  contY: 6
  battX: 23
  battY: 10
  resetX: 15
  resetY: 6
  onoffX: 31.5
  onoffY: 6

points:
  key:
    padding: cy + spacing
    spread: cx + spacing
  zones:
    matrix:
      #Fixes PCB placement in KiCAD
      anchor:
        shift: [100, -100]
      columns:
        first:
          rows.only.skip: true
          key:
            stagger: 0
            column_net: P104 
        second:
          rows.only.skip: true
          key:
            stagger: 2
            column_net: P113 
        third:
          rows.only.skip: true
          key:
            stagger: 11
            # origin: [-10, 14]
            # splay: -2
            column_net: P115
        fourth:
          rows.only.skip: true
          key:
            stagger: 5
            # origin: [-10, 14]
            # splay: -2
            column_net: P002 
        fifth:
          rows.only.skip: true
          key:
            stagger: -6
            # origin: [-10, 18]
            # splay: -2
            column_net: P029
        sixth:
          rows.only.skip: true
          key:
            stagger: -2
            column_net: P031
      rows:
        only:
          row_net: P106
        bottom:
          row_net: P009
        home:
          row_net: P010
        top:
          row_net: P111
    thumbcluster:
      anchor:
        ref: matrix_sixth_bottom
        shift: [-44, -18]
        rotate: 0
      columns:
        first:
          key:
            column_net: P115
        second:
          key:
            stagger: 1
            column_net: P002
        third:
          key:
            stagger: -1
            origin: [-9, -9]
            splay: -10
            column_net: P029
        fourth:
          key:
            stagger: -2
            origin: [-9, -9]
            splay: -10
            column_net: P031
      rows:
        only:
          row_net: P106
  mirror:
    ref: matrix_sixth_top
    distance: 100

outlines:
  keys:
    - what: rectangle
      where: true
      size: [14, 14]
      fillet: 0
  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        # Top
        - ref: matrix_first_top
          shift: [-padX, padY]
        - ref: matrix_second_top
          shift: [0.4padX, padY]
        - ref: matrix_third_top
          shift: [-padX, padY]
        - ref: matrix_third_top
          shift: [0.4padX, padY]
        - ref: matrix_fourth_top
          shift: [-padX, padY]
        - ref: matrix_fourth_top
          shift: [padX, padY]
        - ref: matrix_fifth_top
          shift: [-0.4padX, padY]
        - ref: matrix_fifth_top
          shift: [4padX, padY]

        # Bottom
        - ref: thumbcluster_fourth_only
          shift: [1.3padX, padY]
        - ref: thumbcluster_fourth_only
          shift: [padX, -padY]
        - ref: thumbcluster_fourth_only
          shift: [-padX, -padY]
        - ref: thumbcluster_first_only
          shift: [padX, -padY]
        - ref: thumbcluster_first_only
          shift: [-padX, -padY]
        - ref: matrix_first_bottom
          shift: [2padX, -padY]
        - ref: matrix_first_bottom
          shift: [-padX, -padY]

        # Connect to top
        - ref: matrix_first_top
          shift: [-padX, -padY]
    
  board_left_w/_keys:
    - name: board_left
    - operation: subtract
      name: keys
  board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        # Top
        - ref: mirror_matrix_first_top
          shift: [-padX, padY]
        - ref: mirror_matrix_second_top
          shift: [0.4padX, padY]
        - ref: mirror_matrix_third_top
          shift: [-padX, padY]
        - ref: mirror_matrix_third_top
          shift: [0.4padX, padY]
        - ref: mirror_matrix_fourth_top
          shift: [-padX, padY]
        - ref: mirror_matrix_fourth_top
          shift: [padX, padY]
        - ref: mirror_matrix_fifth_top
          shift: [-0.4padX, padY]
        - ref: mirror_matrix_fifth_top
          shift: [4padX, padY]
        
        # Bottom
        - ref: mirror_thumbcluster_fourth_only
          shift: [1.3padX, padY]
        - ref: mirror_thumbcluster_fourth_only
          shift: [padX, -padY]
        - ref: mirror_thumbcluster_fourth_only
          shift: [-padX, -padY]
        - ref: mirror_thumbcluster_first_only
          shift: [padX, -padY]
        - ref: mirror_thumbcluster_first_only
          shift: [-padX, -padY]
        - ref: mirror_matrix_first_bottom
          shift: [2padX, -padY]
        - ref: mirror_matrix_first_bottom
          shift: [-padX, -padY]

        # Connect to top
        - ref: mirror_matrix_first_top
          shift: [-padX, -padY]

  board_right_w/_keys:
    - name: board_right
    - operation: subtract
      name: keys

pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
    # Choc switches
      choc_hotswap:
        what: choc
        where: /^(matrix_|thumbcluster_).*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      # Main diodes
      diode:
        what: diode
        where: /^(matrix_|thumbcluster_).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [diodeX, -diodeY]
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: down
        where:
          ref: matrix_sixth_top
          shift: [contX, -contY]
          rotate: -90
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_sixth_bottom
          shift: [battX, -battY]
          rotate: 180
        params:
            pos: pos
            neg: GND
      # Reset button
      reset_button:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: matrix_sixth_bottom
          shift: [resetX, resetY]
          rotate: -90
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
            ref: matrix_sixth_bottom
            shift: [onoffX, onoffY]
            rotate: -90
        params:
            from: pos
            to: RAW
      # # Write "Beans V2" on the PCB
      # front_text: &text
      #   what: text
      #   where: &textWhere
      #       ref: matrix_sixth_bottom
      #       shift: [13, -11]
      #   params: &textParams
      #       text: Beans V2
      #       justify: left
      #       h_size: 2.0
      #       v_size: 2.0
      #       thickness: 0.4
      # Write "Beans V2" on the PCB
      name_text: &text
        what: text
        where: &textWhere
            ref: matrix_fourth_bottom
            shift: [-8, -13]
        params: &textParams
            text: Beans V2
            justify: left
            h_size: 2.0
            v_size: 2.0
            thickness: 0.3
  right:
    outlines:
      main:
        outline: board_right
    footprints:
    # Choc switches
      choc_hotswap:
        what: choc
        where: /^(mirror_matrix_|mirror_thumbcluster_).*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      # Main diodes
      diode:
        what: diode
        where: /^(mirror_matrix_|mirror_thumbcluster_).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-diodeX, -diodeY]
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: mirror_matrix_sixth_top
          shift: [contX, -contY]
          rotate: 90
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: mirror_matrix_sixth_bottom
          shift: [battX, -battY]
          rotate: 180
        params:
            pos: pos
            neg: GND
      # Reset button
      reset_button:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: mirror_matrix_sixth_bottom
          shift: [resetX, resetY]
          rotate: -90
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
            ref: mirror_matrix_sixth_bottom
            shift: [onoffX, onoffY]
            rotate: -90
        params:
            from: pos
            to: RAW